project:
  type: website
  output-dir: docs

website:
  title: "Pierre-Yves de Müllenheim"
  site-url: https://www.pydemullenheim.com
  description: "Movement, wearables, programming"
  open-graph: true
  reader-mode: true
  repo-url: https://github.com/pydemull/website-quarto
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Scientific works"
        menu: 
        - pubs.qmd
        - coms.qmd
      - text: "Posts"
        menu:
        - href: posts.qmd
          text: "Blog"
        - href: in_posts.qmd
          text: "LinkedIn"
    right: 
    - text: "{{< iconify ph butterfly-bold size=1.2em title='Bluesky' >}}"
      href: https://bsky.app/profile/pydemullenheim.com
    - text: "{{< iconify fa6-brands square-x-twitter size=lg >}}"
      href: https://twitter.com/pydemullenheim
    - text: "{{< iconify fa6-brands mastodon size=lg >}}"
      href: https://fosstodon.org/@pydemullenheim
    - text: "{{< iconify fa6-brands linkedin size=lg >}}"
      href: https://www.linkedin.com/in/pierre-yves-de-m%C3%BCllenheim-03a75572
    - text: "{{< iconify fa6-brands github size=lg >}}"
      href: https://github.com/pydemull
    - text: "{{< iconify academicons google-scholar-square size=lg >}}"      
      href: https://scholar.google.com/citations?hl=fr&user=XrIzAj8AAAAJ
    - text: "{{< iconify fa6-brands researchgate size=lg >}}"
      href: https://www.researchgate.net/profile/Pierre-Yves-De-Muellenheim-2
  page-footer: 
    center: "Copyright © 2022-2025 Pierre-Yves de Müllenheim"
    background: primary
    foreground: "white"
  favicon: img/logo.ico
  twitter-card: true

format:
  html:
    theme: minty
    css: css/website.css
    toc: true

editor: visual

