project:
  type: website
  output-dir: docs

website:
  title: "Pierre-Yves de Müllenheim"
  site-url: https://www.pydemullenheim.com
  description: "Movement, wearables, programming"
  open-graph: true
  reader-mode: true
  repo-url: https://github.com/pydemull/website-quarto
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog posts (EN)
      - in_posts.qmd
      - href: pubs.qmd
        text: Publications
      - href: coms.qmd
        text: Communications
    right: 
    - text: "{{< iconify arcticons bluesky  size=lg >}}"
      href: https://bsky.app/profile/pydemullenheim.bsky.social
    - text: "{{< iconify fa6-brands square-x-twitter size=lg >}}"
      href: https://twitter.com/pydemullenheim
    - text: "{{< iconify fa6-brands mastodon size=lg >}}"
      href: https://fosstodon.org/@pydemullenheim
    - text: "{{< iconify fa6-brands linkedin size=lg >}}"
      href: https://www.linkedin.com/in/pierre-yves-de-m%C3%BCllenheim-03a75572
    - text: "{{< iconify fa6-brands github size=lg >}}"
      href: https://github.com/pydemull
    - text: "{{< iconify academicons google-scholar-square size=lg >}}"      
      href: https://scholar.google.com/citations?hl=fr&user=XrIzAj8AAAAJ
    - text: "{{< iconify fa6-brands researchgate size=lg >}}"
      href: https://www.researchgate.net/profile/Pierre-Yves-De-Muellenheim-2
  page-navigation: true
  page-footer: 
    center: "Copyright © 2022-2023 Pierre-Yves de Müllenheim"
    background: primary
    foreground: "white"
  favicon: img/logo.ico
  twitter-card: true
  google-analytics: 
    tracking-id: "G-7HEZQCLYGS"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: light

format:
  html:
    theme: minty
    css: css/website.css
    toc: true

editor: visual

