project:
  type: website
  output-dir: docs

website:
  title: "Pierre-Yves de Müllenheim"
  site-url: https://www.pydemullenheim.com
  description: "Movement, wearables, programming"
  reader-mode: true
  repo-url: https://github.com/pydemull/website-quarto
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - about.qmd
      - pubs.qmd
      - coms.qmd
      - in_posts.qmd
    right: 
    - icon: twitter
      href: https://twitter.com/pydemullenheim
    - icon: linkedin
      href: https://www.linkedin.com/in/pierre-yves-de-m%C3%BCllenheim-03a75572
    - icon: github
      href: https://github.com/pydemull
  page-navigation: true
  page-footer: 
    center: "Copyright © 2022-2023 Pierre-Yves de Müllenheim"
    background: primary
    foreground: "white"
  favicon: img/logo.png
  twitter-card: true
  opengraph: true
  google-analytics: 
    tracking-id: "G-7HEZQCLYGS"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: headline
    palette: light

format:
  html:
    theme: minty
    css: css/website.css
    toc: true

editor: visual

